### ISSUE TITLE
[Bug]:  Compat Issue with Async and MobAI

### ISSUE THREAD

**Issue by suerion** [someaddons/cupboard#20]
### Describe the bug you're experiencing

Hey, i'm helping on fixing Compat issues with some mods. We had an issue on Async, Cupboard and MobAI and other Mob Adding Mobs

On Line 5114, 5148, 5928 etc,
https://mclo.gs/kPh0CTc

Here you could look on the issues 
https://github.com/AxalotLDev/Async/issues/1
```
[11:51:18] [Async-Tick-Pool-Thread-19/WARN]: A mod is trying to add an entity from offthread, this should be avoided. Printing trace:
java.lang.Exception: null
	at knot/net.minecraft.class_3218.handler$cib000$cupboard$OnaddEntity(MixinServerLevel.java:1786) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_14175(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_8649(MixinServerLevel.java:893) ~[server-intermediary.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.ability.active.offensive.GhastlyAbility.onAbilityUse(GhastlyAbility.java:65) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.register.EldritchMobsEventListeners.lambda$init$4(EldritchMobsEventListeners.java:64) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.ability.callback.onAbilityUseCallback.lambda$static$0(onAbilityUseCallback.java:13) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.minecraft.class_1309.handler$cnf000$eldritch_mobs$useActiveAbilities(class_1309.java:21444) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2595) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.mixinextras$bridge$method_5773$316(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.wrapOperation$glb001$porting_lib_entity$preEntityTick(MixinServerLevel.java:22307) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_18762(MixinServerLevel.java:770) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:93) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at knot/com.axalotl.async.serdes.SerDesRegistry$DefaultFilter.serialise(SerDesRegistry.java:232) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$4(ParallelProcessor.java:93) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[11:51:18] [Async-Tick-Pool-Thread-19/WARN]: A mod is trying to add an entity from offthread, this should be avoided. Printing trace:
java.lang.Exception: null
	at knot/net.minecraft.class_3218.handler$cib000$cupboard$OnaddEntity(MixinServerLevel.java:1786) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_14175(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_8649(MixinServerLevel.java:893) ~[server-intermediary.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.ability.active.offensive.StormyAbility.onAbilityUse(StormyAbility.java:57) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.register.EldritchMobsEventListeners.lambda$init$4(EldritchMobsEventListeners.java:64) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.hyper_pigeon.eldritch_mobs.ability.callback.onAbilityUseCallback.lambda$static$0(onAbilityUseCallback.java:13) ~[eldritch-mobs-1.16.1.jar:?]
	at knot/net.minecraft.class_1309.handler$cnf000$eldritch_mobs$useActiveAbilities(class_1309.java:21444) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1309.method_5773(class_1309.java:2595) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_1308.method_5773(class_1308.java:372) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.mixinextras$bridge$method_5773$316(MixinServerLevel.java) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.wrapOperation$glb001$porting_lib_entity$preEntityTick(MixinServerLevel.java:22307) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3218.method_18762(MixinServerLevel.java:770) ~[server-intermediary.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$3(ParallelProcessor.java:93) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at knot/com.axalotl.async.serdes.SerDesRegistry$DefaultFilter.serialise(SerDesRegistry.java:232) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at knot/com.axalotl.async.ParallelProcessor.lambda$callEntityTick$4(ParallelProcessor.java:93) ~[async-0.1.1+alpha.2-1.21.1.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

### Reproducability

Use the Mob Adding Mods

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1  on 0.16.7

### Modloader version

Fabric

### Logs

https://mclo.gs/kPh0CTc

**Comment by suerion** [comment]
![image](https://github.com/user-attachments/assets/9d0c9566-42d6-453e-b35f-bd88ff028c4d)
Here with the issue and Better Fabric Console

**Comment by someaddons** [comment]
That is not a compat issue, its a warning that the mod is doing something broken. As for the async mod it'll never work and always break things, esp with other mods.
